### PR TITLE
refactor: improve rich-select component

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/12gwe16

Improve focus state for dropdown and its list
image

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by Highjhacker** [comment]
@leMaur Quick question ; I can easily navigate between the menu options while pressing my `tab` key, but whenever I press `enter` or `space` (tried a bunch of buttons cause I wasn't sure on the exact key on mac) it just doesn't select the highlighted option, is that for a separate PR or should it work here already ?

**Comment by ItsANameToo** [comment]
@leMaur see question above

**Comment by leMaur** [comment]
> @leMaur Quick question ; I can easily navigate between the menu options while pressing my `tab` key, but whenever I press `enter` or `space` (tried a bunch of buttons cause I wasn't sure on the exact key on mac) it just doesn't select the highlighted option, is that for a separate PR or should it work here already ?

🤔 should be work... let me check

**Review by Highjhacker — APPROVED** [review]
Working as expected :toot:

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
