### PR TITLE
refactor: allow to specify a right sided label for the toggle component

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

Allow us to specify a right label for the `x-ark-toggle` component : 

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — COMMENTED** [review]
does this make the switch obsolete? should it be removed? or should the switch component be updated to work as intended?

**Comment by Highjhacker** [comment]
@ItsANameToo Feel like the switch is useless, I don't see it used anywhere 🤔 I'd remove it, but let me know what you want ?

**Comment by ItsANameToo** [comment]
compare the switch with the toggle. Are they identical? then you can remove it and use the toggle. But if the switch styling differs (e.g. it doesn't have an on/off state but a blue color at either side and just points into one direction to indicate which is active), then it needs to be updated to work again @Highjhacker

**Comment by Highjhacker** [comment]
They differ a bit, but need to check exactly how (need to fix it first), but again, that component is used nowhere in our apps / libs 🤔

**Comment by ItsANameToo** [comment]
it's used, that's why you are opening this PR in the first place

**Pull request closed without merging**
