### PR TITLE
feat: honey-pot component

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

New `<x-honey-pot />` component allowing us to prevent spam when included within our forms. 

Had to make it custom cause the original component (from https://github.com/lukeraymonddowning/honey) just didn't worked, so @faustbrian took a look at it.

Related to https://app.clickup.com/t/kvdtx7

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by leMaur** [comment]
@ItsANameToo Can you add a ClickUp tasks? Just out of my curiosity, is there a reason why you choose [Honey from Luke Downing](https://github.com/lukeraymonddowning/honey) and not from [Spatie](https://github.com/spatie/laravel-honeypot)? for the re-captcha integration?

**Comment by ItsANameToo** [comment]
you mean @Highjhacker @leMaur ? :bleh:

**Comment by leMaur** [comment]
Oh gosh! @ItsANameToo sorry

**Comment by Highjhacker** [comment]
@leMaur Forgot to add it, it's related to https://app.clickup.com/t/kvdtx7, will update the description of this PR.

As for the reason, spatie honeypot wasn't working at all with that component being Livewire now, I was losing focus on every fields within the form because of the `@honey` directive, and while digging a bit for that package, it seems that they don't have anything out of the box to handle livewire, while this package does.

**Comment by ItsANameToo** [comment]
draft until no longer `wip`

**Pull request merged**
