### PR TITLE
refactor: make contact form into livewire component

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

https://app.clickup.com/t/kvdtx7

Following task related to Throttling can be found here : https://app.clickup.com/t/wtkprj

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@ItsANameToo do you think it's worth converting this page to Livewire? Or @Highjhacker at the very least for this task, could you see if there's a way to trigger the alert without having it be triggered in the blade component? 🤔 it never used to alert like this, so triggering it from within the button no longer makes sense

**Comment by ItsANameToo** [comment]
@Highjhacker can you check alex's suggestion of moving to livewire for this form

**Comment by Highjhacker** [comment]
Gave it a go @ItsANameToo , if good enough I'll finish it tomorrow morning

**Comment by Highjhacker** [comment]
@ItsANameToo Almost good to go but need your input on two things ; 

1) Do we want real time validation instead of validation on submit ? 
2) I have an issue with the `@honeypot` directive within the form, basically, it cause a lose of focus on any input you are typing on, and it's pretty annoying, so as far as I can tell, there's two solutions to that issue ; 

- 1) We could change the following to `false`, which would solve this issue, but I'm afraid it might cause some unwanted things so it doesn't really seems ideal 🤔 

```php
/*
     * When this is activated there will be a random string added
     * to the name_field_name. This improves the
     * protection against bots.
     */
    'randomize_name_field_name' => env('HONEYPOT_RANDOMIZE', true),
```

- 2) Apparently would be fixed if we moved the form opening/closing outside the livewire component 🤔 

https://github.com/spatie/laravel-honeypot/issues/68

**Comment by ItsANameToo** [comment]
@Highjhacker 
1. realtime when it makes sense. If we show a toast then realtime will only become a mess. Compare to other forms we use and decide what would be useful for the contact form
2. > Apparently would be fixed if we moved the form opening/closing outside the livewire component

I don't understand what you mean with the above statement

**Comment by Highjhacker** [comment]
> @Highjhacker
> 
> 1. realtime when it makes sense. If we show a toast then realtime will only become a mess. Compare to other forms we use and decide what would be useful for the contact form
> 2. > Apparently would be fixed if we moved the form opening/closing outside the livewire component
> 
> I don't understand what you mean with the above statement

I'll check for 1), but I'd say that it's fine as it is for a contact form. As for 2), I was quoting a possible solution from that github issue, from what I've understood, instead of having the <form></form> within the the Livewire component, it would work if we did something like 

```html
    <form>
        <livewire:component />
    </form>
```

And the issue with `@honeypot` would be solved.

**Comment by ItsANameToo** [comment]
@Highjhacker have you tested if it fixes the honeypot issue when you move it around as suggested?

**Comment by Highjhacker** [comment]
> @Highjhacker have you tested if it fixes the honeypot issue when you move it around as suggested?

Yeah, and was still losing focus (with the <form> tags moved around and the @honeypot directive included, will check now on the other option and how it would work out.

**Comment by Highjhacker** [comment]
1. Is working, so basically setting `HONEYPOT_RANDOMIZE=false` within our .env on MSQ would fix that loss of focus. What would you like more, want me to investigate the other package @ItsANameToo ?

**Comment by ItsANameToo** [comment]
@Highjhacker check if the package works with the contact form

**Comment by Highjhacker** [comment]
@ItsANameToo Report of the current state of things ; 

Thanks to @faustbrian I was able to get the package to work, something was funky there, but he managed to fix it, so now I can make it work on MSQ, but not here yet, not sure of why exactly but whenever I tried to extract it there I couldn't make it work at all, so will have a fresh look tomorrow on that 🤔

**Comment by Highjhacker** [comment]
@ItsANameToo Made it into a separate PR ; https://github.com/ArkEcosystem/laravel-ui/pull/552

So, from there, once approved, I can use it here to make use of that component within our Contact component, and it should be good to go.

**Comment by ItsANameToo** [comment]
@Highjhacker add to the readme that you need to run 

```
php artisan honey:install
php artisan migrate
```

in order to work with the honey directive as it is currently undocumented

**Comment by ItsANameToo** [comment]
@Highjhacker maybe remove https://github.com/ArkEcosystem/laravel-ui/pull/552/files#diff-37b25d7205f723866d930085fb6cb9419c5910c976f9368d815bcc29e9be3066R1 too as that's currently not used at all (unless you add to the readme how this config can be moved over to the right location, but I doubt that's of any use if you can run `php artisan honey:install` to get it too)

**Comment by ItsANameToo** [comment]
handled in https://github.com/ArkEcosystem/laravel-ui/pull/561

**Comment by Highjhacker** [comment]
@ItsANameToo Tests failing cause of the `WithHoney` trait I had to add within the livewire `ContactForm` component, thing is, we don't have access to that package anymore from here, but we do from MSQ since we installed the dependency. But that trait is required to be implemented within the Livewire component related to the form where we use our honey-pot component. Any idea here ? 🤔

**Comment by ItsANameToo** [comment]
@Highjhacker ignore the coverage for the contact form in the UI lib and test it in the projects itself that make use of it. Forcing everything to include the honeypot dependency and migration while not even making use of it feels wrong so I want to avoid that

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
@Highjhacker I'm having issues getting this to work. These are the steps I followed:

- pulled this PR
- updated composer.json with `"arkecosystem/ui": "dev-fix/contact-button-disappearing-on-submit as 3.200",`
- installed dep `composer require lukeraymonddowning/honey --ignore-platform-reqs`
- `php artisan honey:install`
- `php artisan migrate`
- went to contact page and busted:

image

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
@Highjhacker the form should clear, or some sort of throttling should be in place 🤔 I'd perhaps start with clearing the form and add throttling later on but maybe check with Rok and/or Michel to confirm

image

Commented this to the msq PR but more relevant here I think

**Comment by Highjhacker** [comment]
Asked @ItsANameToo and throttling will be handled in a separate PR, will create a card for it now.

**Comment by alexbarnsley** [comment]
Did you create the card @Highjhacker? It's worth linking here if so

**Comment by alexbarnsley** [comment]
Since the throttling will be another card, I think this looks good now 🤔 will approve both PRs

**Review by alexbarnsley — APPROVED** [review]

**Comment by Highjhacker** [comment]
@alexbarnsley I did, forgot to post it here ; https://app.clickup.com/t/wtkprj

**Comment by ItsANameToo** [comment]
can you open PRs on the other projects that make use of the contact form to update them to use this new one @Highjhacker

**Comment by Highjhacker** [comment]
Will do now @ItsANameToo

**Comment by Highjhacker** [comment]
@ItsANameToo Done 👍

**Review by ItsANameToo — APPROVED** [review]

**Comment by ItsANameToo** [comment]
partial follow up for the spam handling: https://github.com/ArkEcosystem/laravel-ui/pull/639

**Pull request merged**
