### PR TITLE
feat: pagination with search form

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Shows a search form when the user clicks the `...` or the "page N of N" buttons

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
A few remarks:
- can you remove the arrow up/down stuff that gets added to number inputs in browsers?
image

- when hovering over the `...` it should change to a search icon like explorer has
image

- in dark mode the input text is difficult to read
image

- these feel a little thin (and barely visible but might be the thickness instead of the color) + can you add a `transition-default` class to them so they have a smooth transition when hovering over them
image

- when I am on the first page and then click the last page in the pagination component, I run into an error and it messes with the component: `DOMException: Failed to execute 'setAttribute' on 'Element': '@click' is not a valid attribute name`
image

- we have 2 pagination components, one uses livewire `pagination.blade.php` while the other one uses posts for regular pagination `pagination-url.blade.php`, you'll have to make the changes to the pagination-url file too

**Comment by alfonsobries** [comment]
@ItsANameToo ✅

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
can you update these bottom row buttons so they take the same height as the top row 
image

other than that it looks good now

**Comment by alfonsobries** [comment]
@ItsANameToo done,

Let me know when this is related so I can update the explorer (and the rest of the projects that use pagination)

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
