### PR TITLE
fix: markdown editor not counting characters

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/pzfdqd

The issue was related to the recently added `customHTMLSanitizer` it was properly removing the HTML added on the preview but also removing the HTML used to count the characters.

~~This PR implements an alternative patch to remove the preview. (There is no native way to disable it or at least I was unable to find it in the docs, editor source code, etc)~~

Update:

1. Creates a new API endpoint that uses our markdown parser to count the words and characters
2. Every time the user updates the markdown it will use the API to get the count
3. Implements throttling

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by Highjhacker — APPROVED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
Although the counter works again, it's not in line with the backend counter, e.g:
image

will post the full text on clickup, contains a bunch of html that the editor might not be counting but the backend is

**Comment by alfonsobries** [comment]
@ItsANameToo ✅  (also updated PR description)

**Review by crnkovic — COMMENTED** [review]
@alfonsobries can you also add the test to make sure it properly counts if no markdown is entered? So 2 uses cases where no `markdown` field is even in the request payload and when `markdown` is set to an empty string.

Also, is `HandlesMarkdown` the right name? Something just feels off to me. 🤔 Maybe something like `ParsesMarkdown` or similar would make more sense 🤔 Let me know what you think.

**Comment by alfonsobries** [comment]
@crnkovic test added!, about the name mmm I am not sure about `ParsesMarkdown ` since the trait also counts the characters, tomorrow ill revisit this PR and think again

**Comment by alfonsobries** [comment]
@crnkovic after thinking about this I agree with you that `ParsesMarkdown` is better, the other one is too general so I just updated it. Let see if other reviewer think different

**Comment by Highjhacker** [comment]
@alfonsobries Was just trying the latest changes with the text document @ItsANameToo joined to the clickup task, it does seems to count the characters properly, but plenty of errors are being thrown in the console when I scroll within the editor as shown in the .gif below :

**Comment by alfonsobries** [comment]
@Highjhacker just fixed the exception

Plus: since I recently updated the scrollbar settings on my mac noticed a weird scrollbar that I am fixing by applying the custom scrollbar we use on other elements, may be worth taking a look at this change cc @ItsANameToo 

### Before:
image

### After:
image

**Comment by Highjhacker** [comment]
It's me again @alfonsobries :sadup: 



Other than that, looks better with the custom scrollbar :lala:

**Comment by alfonsobries** [comment]
@Highjhacker one more 😅

**Review by Highjhacker — APPROVED** [review]
Tested again with the document provided by Mici, and all good, no more console error and count seems good to me :toot:

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
