### PR TITLE
refactor: allow new lines within user-tagger component

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

https://app.clickup.com/t/hq4k2k

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
I don't think this is working, i have the same result as in the clickup card 🤔 

image

image

**Edit:** I've confirmed I have the `white-space: pre-wrap` change

**Comment by Highjhacker** [comment]
@alexbarnsley Probably misunderstood the task then 🤔 My understanding was the following ; 

1) User input the following as review :

```
a
a
a
```

2) That multi lines review is deplayed as it in the `Reviews` section
3) But prior to this PR, whenever you wanted to update the review, everything was turned into a single line, even if the original review left was spread on multple lines, so I changed this to reflect properly how it looks during the update of the review, which seems to works given your screenshot so a bit confused here :joy:

**Comment by alexbarnsley** [comment]
@Highjhacker no I think you're right. I missed the second image in the card, so I think your PR fixes this issue in that

I think it may be worth also looking at the spacing after saving so it's consistent between viewing and editing the review body (it may not be in the ui dep that's causing the lack of spacing when viewing)

image

**Comment by Highjhacker** [comment]
@alexbarnsley Yeah, need to adjust that in MSQ with `whitespace-pre-wrap`, gonna open a PR right now and passing this one as ready for review :lala:

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
