### PR TITLE
fix: dont init alpine by default on the inputs

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/f33pj6

A `x-data` property that was added to the input component on this PR: https://github.com/ArkEcosystem/laravel-ui/pull/309 is causing conflicts with other alpine components that includes an input, a specific case in the register form password rules that are not being shown as described on this ticket https://app.clickup.com/t/f33pj6.

Made different test under different circumstances (inside an alpine component, without an alpine component, etc) and apparently, that attribute was not necessary the tooltip still works so most likely can be safely removed

Once merged can be tested by updating this dependency on msq and be write a password in the register form, it should show the password rules.

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — APPROVED** [review]

**Comment by ItsANameToo** [comment]
@alfonsobries the issue with not initializing alpine on the input is that there is a `$refs.input_field.focus()` that will no longer work (idea is that you can click the error icon and it will focus the input field). We can probably resolve this by ensuring alpine is always initialized in a parent, but we will need to explicitly mention this in order to have consistent error icon responsiveness throughout applications. 

so:
- either we should add a property to override the alpine initialization on the input so it will have `x-data="{}"` by default but we can ignore initializing it if we already do that (e.g. for the password issue)
- or we remove the initialization and have to add to the readme that for a consistent experience the parent should always initialize the alpine data

**Comment by alexbarnsley** [comment]
@alfonsobries Something else to note, moving the `x-data="{}"` to further up such as the form level (`<form x-data="{}">`), you still have the problem where there will possibly be multiple fields with the same ref since `ref="input_field"` is generic. I think Michel's suggestion of allowing to disable the init will work as long as it's only disabled for 1 field

A possible solution to all these things would be to change it so that each ref is unique based on name/id so there are no duplicates. I remember trying this but I don't remember why I went with a generic name instead

**Comment by alfonsobries** [comment]
@ItsANameToo @alexbarnsley ah ok,  I was misunderstanding the reason for that attribute, I thought it was just for the tooltip to work. Ill look for an alternative solution in a moment

**Comment by alfonsobries** [comment]
@ItsANameToo @alexbarnsley ready, basically I changed the selector to use the id of the input and the native onclick event so it doesn't need alpine at all

Quick note: You may think using the ID as the selector may be a problem if we have the same id twice on the page if that is ever a case we should solve the reason behind having the same id twice on a page since that shouldn't b happening.

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
